services:
  database:
    image: postgres:${POSTGRES_VERSION}
    volumes:
      - modi-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 30s
      retries: 6
    restart: always

  modi:
    build: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
        mailer:
          condition: service_started
        database:
          condition: service_healthy
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  mailer:
    build: .
    command: celery -A accounts worker -l info
    depends_on:
      - broker
    restart: always

  broker:
    image: redis:${REDIS_VERSION}
    restart: always

volumes:
  modi-postgres-data:
