services:
  database:
    image: postgres:${POSTGRES_VERSION}
    volumes:
      - modi-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  modi:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - database
      - mailer
    command: ["./wait-for-it.sh", "database:5432", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]

  mailer:
    build: .
    command: celery -A accounts worker -l info
    volumes:
      - .:/code
    depends_on:
      - broker
    restart: always

  broker:
    image: redis:${REDIS_VERSION}
    restart: always

volumes:
  modi-postgres-data:
